Repository Johncakes/Open_Source_Group_8, pull requests merged in 2025-06, with the labels that each got.

#27 Feature/search
  config/templates/Components/navbar.html
  config/templates/search.html
  movie/urls.py
  movie/views.py
Labels: feature

#29 header, footer 링크 추가, 별점 0.5단위 시각화
  config/templates/Components/footer.html
  config/templates/Components/navbar.html
  config/templates/feature_detail_page.html
  movie/views.py
Labels: feature

#32 Ruff 기반 포맷팅 반영
  config/asgi.py
  config/settings/default.py
  config/urls.py
  config/wsgi.py
  movie/migrations/0002_movie_moviecast_moviecrew.py
  movie/migrations/0003_review.py
  movie/models/__init__.py
  movie/models/review.py
  movie/scripts/fetch_genres.py
  movie/scripts/fetch_movie_details.py
  movie/scripts/fetch_popular_movies.py
  movie/scripts/import_genres.py
  movie/scripts/import_movies.py
  movie/urls.py
  movie/views.py
  pyproject.toml
Labels: formatting

#55 [PROD] Hotfix/1.0.1
  account/forms.py
  movie/views.py
Labels: hotifx

#54 [DEV] Hotfix/1.0.1
  account/forms.py
  movie/views.py
Labels: hotifx
